### ISSUE TITLE
Not working ?? 

### ISSUE THREAD

**Issue by cormad** [theminor/node-red-contrib-tcc-honeywell#2]
Hey John, 

I can't seem to get this to work in Node Red, could you share your flow ?? 
Thanks 
Jeff

**Comment by theminor** [comment]
> I can't seem to get this to work in Node Red, could you share your flow ??

I'm no longer running Node Red, so I don't really have a flow to share. There might have been some changes with the Honeywell API that I'm not aware of. Also, as noted in the [readme](https://github.com/theminor/node-red-contrib-tcc-honeywell/blob/master/README.md), I was never able to actually change settings, only read from the API.

If you want to work on this project more, it would be welcomed! There are a couple of other github projects on the Honewell TCC model that could point you in the right direction if you want to fork the code...

**Comment by theminor** [comment]
@cormad Please try it now - another person just submitted a pull request that reportedly fixes it. If it is now working, please let me know or close this issue. Thanks!

**Comment by cspawn1** [comment]
Any updates on if this is working? I have a project that I'll be using about 18 of these in NodeRed

**Comment by arriflex** [comment]
Not working consistently for me, crashes node red unpredictably. I seem to have a callback error with node-red v1.2.3 in the nodered/node-red docker container:

`TypeError: callback is not a function
    at /usr/src/node-red/node_modules/node-red-contrib-tcc-honeywell/node-tcc-honeywell.js:40:5
    at Request._callback (/usr/src/node-red/node_modules/node-red-contrib-tcc-honeywell/node-tcc-honeywell.js:31:4)
    at Request.self.callback (/usr/src/node-red/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/src/node-red/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/src/node-red/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)`

**Comment by theminor** [comment]
@arriflex sorry to hear that! If you find a solution, please let me know and I'll be happy to merge it. I don't run this anymore so I don't have a reliable method to test and debug it...

**Comment by arriflex** [comment]
Thanks, I will. Given my poor familiarity with js I suspect I'm more likely to find an alternative means of capturing the data. I'm lazy and running the node-red for scraping the Honeywell data and sending to Influx in its own container allows me to simply restart on failures automatically. In general it seems to fail a couple times per day unless I'm in node-red changing hitting deploy where it seems to happen considerably more often. 

It was all working fine until I decided to update what apparently was a very out of date node-red (pre 1.0) to current and encountered the crashes. 

Thanks for your having put it together in the first place, I was using scraping the website using a Ruby script before I found this apparently not long after you shared it!

**Comment by catstitan** [comment]
The crashing problem seems to be related to how often the node is called. If you limit the frequency to no more than once every 5 minutes it seems to be stable.

**Comment by theminor** [comment]
Thanks - I have added this info to the ReadMe
